### ISSUE TITLE
—Card-mod-Icon doesn’t update in realtime

### ISSUE THREAD

**Issue by Maddin1684** [thomasloven/lovelace-card-mod#334] opened 2023-12-30 14:48 UTC
Hey,

with the actual version of card_mod my icons doesn’t update in realtime. When I open a door, the icon doesn’t change instantly. 

With the previous version there are no problems and everything works fine. 

>       - entity: binary_sensor.garagentur
        icon: mdi:garage-variant
        secondary_info: last-changed
        card_mod:
          style:
            hui-generic-entity-row:
              $: |
                .text-content:not(.info) {
                   color:
                      {% if is_state(config.entity, 'off') %}
                       white
                       {% else %}
                       #ff4040
                     {% endif %}
                     ;
                 }
                :host {
                {% if is_state(config.entity, 'off') %}
                 --paper-item-icon-color: white;
                 --card-mod-icon: mdi:garage-variant;
                  {% else %}
                 --paper-item-icon-color: #ff4040;
                 --card-mod-icon: mdi:garage-open-variant;
                      {% endif %}
                      ;  
                      }

**Comment by thomasloven** [comment] 2023-12-30 16:03
Duplicate of #333.
Please use the issue templates.

**Closed by thomasloven** 2023-12-30 16:03 UTC
