### ISSUE TITLE
version 13 stopped working, going back to 12 fixed issue

### ISSUE THREAD

**Issue by marcelliotnet** [thomasloven/lovelace-card-mod#31] opened 2020-02-14 03:47 UTC
My Home Assistant version: 105.3

My lovelace configuration method (GUI or yaml):

What I am doing:

style: |
  ha-card {
    border-radius: 15px;
    font-size: 12px;
    font-variant: small-caps;
    box-shadow: none;
  }

What I expected to happen:

What happened instead:

**Minimal** steps to reproduce:

updated to 13, rolled back to 12

```yaml
# The least ammount of code possible to reproduce my error



# End of code
```

Error messages from the browser console:

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

[ ] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

[ ] Have made sure I am using the latest version of the plugin.

[ ] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

[ ] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by naamah75** [comment] 2020-02-14 07:59
Same for me, with release 13 I got:

`Uncaught TypeError: Failed to resolve module specifier "card-tools/src/templates.js". Relative references must start with either "/", "./", or "../".`

Rolled back to 12, no issue.

**Comment by warwickofthegh** [comment] 2020-02-14 11:48
same ok thanks, I'll roll back until fix, thanks.

**Comment by warwickofthegh** [comment] 2020-02-15 06:05
Anyone confirm this is fixed in release 14?

**Comment by langestefan** [comment] 2020-02-16 15:32
I am also having issues with release 13. My lovelace button-card (from [https://github.com/custom-cards/button-card](button-card) no longer seem to be functioning properly after updating card-mod to version 13.

**Comment by Spirituss** [comment] 2020-02-26 11:14
I have the same issue with entities objects, while custom:button-card is working well. I tried use version 12, have the same result.

**Comment by brianhanifin** [comment] 2020-02-26 23:13
There error I am getting with version 13 is `"style" is read-only`! Reinstalling version 12 it works again.

```
- type: custom:mod-card
  style: |
    ha-card {
      background: rgba(0, 0, 0, 0.3);
      margin-top: 5px;
      padding-bottom: 20px;
    }
  card:
```

**Closed** 2020-05-04 20:56 UTC

**Comment by warwickofthegh** [comment] 2020-05-13 02:15
what is the status on this one @thomasloven? was there a breaking change or something we need to do different with v13?

**Comment by thomasloven** [comment] 2020-05-13 06:36
How should I know?
The original post contains no information and doesn't follow the template.
Every comment describes a different problem.
Some were definitely fixed in the updated published a few days before the original post. Others, I don't even know what they're trying to say.
In your case; is the problem you agree too the one that isn't described in any detail at all, or the one that was caused by installing the wrong file or hacs failing?

**Comment by thomasloven** [comment] 2020-05-13 06:40
And if your issue isn't fixed by updating to the latest version following the instructions linked from the readme, please open a new issue and describe your problems.
