### ISSUE TITLE
Card-mod causes Energy dashboard to load on half of the screen

### ISSUE THREAD

**Issue by Wesley-Vos** [thomasloven/lovelace-card-mod#304] opened 2023-10-25 21:39 UTC
My Home Assistant version: 2023.11.0b0

My lovelace configuration method (GUI or yaml): GUI

What I am doing: opening the energy dashboard

What I expected to happen: it shows full screen

What happened instead: it is shown half screen because card-mod inserts an element that is in the same flexbox as the actual content

**Minimal** steps to reproduce:
1.  Update to 2023.11.0.b0
2. Open the energy dashboard

```yaml
# The least amount of code possible to reproduce my error
Not appliciable

# End of code
```

Error messages from the browser console:
None

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by firstof9** [comment] 2023-10-26 23:15
Example image:
![image](https://github.com/thomasloven/lovelace-card-mod/assets/1105672/372499b0-2cef-452b-a927-6dbd1d0d94f7)

**Comment by mhoogenbosch** [comment] 2023-10-28 19:39
To be expected, but B1 has the same.

**Comment by Wesley-Vos** [comment] 2023-10-28 19:42
I've already done some digging in the card-mod code as well as the HA changes of the latest releases but didn't came to a solution. If there is someone who can point me in the right direction, I'm more than happy to try to fix it.

**Comment by holdestmade** [comment] 2023-10-30 16:21
Same issue here, on b2

**Comment by firstof9** [comment] 2023-10-30 16:37
> I've already done some digging in the card-mod code as well as the HA changes of the latest releases but didn't came to a solution.

Did you rummage around the frontend repo? That's where it would have been tucked away.

**Comment by Wesley-Vos** [comment] 2023-10-30 19:45
> > I've already done some digging in the card-mod code as well as the HA changes of the latest releases but didn't came to a solution.
> 
> 
> 
> Did you rummage around the frontend repo? That's where it would have been tucked away.

Yes I did but couldn't find a change that might causes this. The closest I got was a removed (assumed unused) parameter from the LovelaceStrategy....

We might raise an issue in the frontend repo asking if they could identify which change might cause this. Fixing this issue would also decrease the number of issues raised on the release day this week.

**Comment by firstof9** [comment] 2023-10-30 20:47
So as a test I commented out card-mod in my config and the energy dash is still hosed, so it's not card-mod.

What other cards do you all have loaded?

**Comment by firstof9** [comment] 2023-10-30 21:00
When I view the source on the energy dash I see something weird that looks like it's causing the flexbox to split in half:

```html
<hui-view id="view"><hui-sidebar-view></hui-sidebar-view><card-mod slot="none"><!---->
      <style>
        <!---->
      <!----></style>
    </card-mod></hui-view>
```
Note the <card-mod> bits.

**Comment by Wesley-Vos** [comment] 2023-10-30 21:03
I'm actually quite sure it is. It is indeed the part you are showing in the latest comment. The card-mod slot element causes the hue-view to show it like another real element and makes the actual energy view take 50% of the screen.

Only commenting card-mod is not enough, you have to invalidate the cache. You can test it by manually dropping the card-mod element in the dev tools of your browser (will be automatically added after a few seconds). You will see that the energy screen goes back to normal

**Comment by Wesley-Vos** [comment] 2023-10-30 21:30
I suspect this change to be the cause, asked there if that is indeed true. https://github.com/home-assistant/frontend/pull/18201

**Comment by holdestmade** [comment] 2023-10-30 21:40
Looking on discord, someone states it's fixed in b3, anyone here tested it yet ?

**Comment by firstof9** [comment] 2023-10-30 22:44
It does in fact seem fixed in b3.

**Comment by Wesley-Vos** [comment] 2023-10-31 08:09
It is not working for me either

**Comment by firstof9** [comment] 2023-11-01 14:35
FYI, Still no good in b6

**Comment by Wesley-Vos** [comment] 2023-11-01 16:15
I personally don’t expect this to be fixed by a core/ frontend release. This issue is specially happening due to card-mod so why should they.

I ‘need’ card-mod for quite some styling on my main dashboards so cannot remove it either. Luckily, it is only the energy dashboard that is effected but still not good

**Comment by lordwizzard** [comment] 2023-11-02 02:26
Funny, that if I refresh/reload the Energy Dashboard page (using the browser refresh/reload) it goes back to normal size. If I go do something else in HA and come back to the Energy page it shrinks back.

**Comment by DieMetRik** [comment] 2023-11-02 08:05
Have the same issue after update to 11.0

**Comment by DaN66O** [comment] 2023-11-02 10:25
I have the same problem after upgrading to core-2023.11.0

**Closed** 2023-11-02 14:04 UTC

**Comment by Wesley-Vos** [comment] 2023-11-02 14:08
Yes, this fixes it! Thanks @thomasloven

**Comment by mhoogenbosch** [comment] 2023-11-02 14:21
Confirmed: 3.2.4 solves the issue.

**Comment by ChristophCaina** [comment] 2023-11-03 06:33
I cannot confirm that this issue has been solved.
I am runnining Card-Mod 3.2.4 and still my Energy Dashboard looks the same.

![image](https://github.com/thomasloven/lovelace-card-mod/assets/26391061/10237ddc-875d-4cb8-9193-83a61cd87166)

Refreshing the Screen (F5) does help, but as soon as you leave the Dashboard and then go back to it, it's using half of the screen size.

**Comment by Wesley-Vos** [comment] 2023-11-03 06:36
For me it was a matter of quite some reloading and clearing the full cache in the browser, did you do that? As soon as the new card-mod file was loaded, everything was fine. The change that is done to fix this issue could not cause the energy screen to load half anymore so it is highly likely it is a cache issue.

**Comment by ChristophCaina** [comment] 2023-11-03 08:05
well... it seems that this time, it was really a cache-thing...
Usually, such things do resolve with a Control+F5 to refresh without cache... this time, it did not work...

Sorry....
