### ISSUE TITLE
--card-mod-icon-color does not work

### ISSUE THREAD

**Issue by comet424** [thomasloven/lovelace-card-mod#187] opened 2022-03-18 12:36 UTC
My Home Assistant version: 0.XX.X
core-2022.3.5
supervisor-2022.03.5
Home Assistant OS 7.5

My lovelace configuration method (GUI or yaml):
yaml

What I am doing:
trying to get icons to switch color like it used to work with the last version of home assistant
also did a cache browsing delete  didnt work

also doesnt work in Chrome or Edge
both need refresh to work

What I expected to happen:
the icon should change color when you toggle the switch

What happened instead:

click the toggle switch it doesnt change color anymore...  worked in the last version of the plugin or Home assistant i cant remember
hit refresh  then it shows the new color..  

```yaml
  - entity: sensor.b_hot_water_tank_state
    name: Hot Water Tank
    icon: mdi:water
    secondary_info: last-updated
    card_mod: null
    style: |
      :host {
      --card-mod-icon-color: 
      {% if states(config.entity) == 'on' %} 
        yellow
      {% elif states(config.entity) == 'off' %}
        red
      {% else %}
        blue
      {% endif %}
      ;
      } 

# End of code
```

Error messages from the browser console:

dont know how to get that

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by ildar170975** [comment] 2022-03-18 17:36
Check this issue: https://github.com/thomasloven/lovelace-card-mod/issues/176

**Comment by comet424** [comment] 2022-03-19 13:04
ok ill rename it..

ya that link is old from feb..  my issue was working a week ago.. till i did  hacs and home assistant updates the other day

**Comment by comet424** [comment] 2022-04-01 01:38
card color still broken  with version 3.4.1  figured latest update fix it.. but nope

you gotta hit F5 to refresh the page to see the color change for some reason..   whats changing  Web browsers?

**Comment by comet424** [comment] 2022-04-03 12:25
so the bug  is in the "icon:"  

it works fine if you dont use a custom icon

so you cant use

icon: <icon name>

if you use the  default icon it can change the color... toggled.  

also if i hit F5 to refresh  it will toggle the screen icon colors like from Green to White back and forth with the refreshs

**Comment by ildar170975** [comment] 2022-04-03 20:31
> it works fine if you dont use a custom icon

Even with a default icon a color is not changed.
```
  - type: entities
    title: Problem 128
    entities:
      - entity: input_boolean.test_boolean
        card_mod:
          style: |
            :host {
                {% if is_state(config.entity,'on') %}
                --card-mod-icon: mdi:shield-off-outline;
                --card-mod-icon-color: red;
                {% else %}
                --card-mod-icon: mdi:shield-remove-outline;
                --card-mod-icon-color: cyan;
                {% endif %}
            }
```
![изображение](https://user-images.githubusercontent.com/71872483/161447256-040d2724-397a-4e1c-a7ae-6840c13ddfdf.png)

![изображение](https://user-images.githubusercontent.com/71872483/161447268-8c6756b9-e158-41cd-859d-8730b0f194e7.png)

Color is changed after F5:
![изображение](https://user-images.githubusercontent.com/71872483/161447308-825e054d-35fd-419a-ad6f-aecd029376bb.png)

**Comment by comet424** [comment] 2022-04-05 00:41
ah ok   ya its messed.. must been  one of the home assistant updates that broke it.. but so far no fix yet ):  so sucks  cuz i use toggle switchs   but you forget whats on or off  lol    
but button card that works  

i like that  u do a change icon when it toggles  need to do that myself.
i dont understand the boolean  etc or the helpers..
always learning

**Comment by comet424** [comment] 2022-05-26 11:28
anyone know if there is a fix yet  or if the card mod is a dead intergrations,  slowly switching away from card mod and just stick with regular green color.. and using button-card... but i did like the card mod  so i had color for on off and unavailable
but think guy is very busy   or maybe no fix..
doesnt work in sfari, IE,Chrome...  and running 8.1 HA OS

**Comment by thomasloven** [comment] 2022-05-30 20:51
Should be fixed now.

**Comment by ildar170975** [comment] 2022-05-30 22:14
Thomas, card-mod-icon & card-mod-color seem to be working properly, thank you!

**Comment by thomasloven** [comment] 2022-05-31 06:28
![K7PmaArVnq](https://user-images.githubusercontent.com/1299821/171107022-67000cfb-95e4-41d6-9a7b-a8b6bd23db49.gif)
Can't reproduce

**Closed** 2022-06-02 07:37 UTC

**Comment by ildar170975** [comment] 2022-06-02 10:18
@comet424
Could you test it with card-mod-theme as I did it?
Because so far I did not succeed...

**Comment by comet424** [comment] 2022-06-02 16:37
@ildar170975 sure ill try it today and see how it goes... 
ill add the thomas code  and ill add the lines to one of mine.. to change the icon ill get back to ya to see if i have same issue

did you also try  clearing the web browser cache?  but ill defiantly try for ya

**Comment by ildar170975** [comment] 2022-06-02 16:49
> did you also try clearing the web browser cache?

I did it plenty of times...
Nest step - I'll try to create a fresh test HA instance with only card-mod installed, may be it's a problem with some other plugins...

**Comment by comet424** [comment] 2022-06-02 17:08
@ildar170975 so i can and can not get that to work..... it wont work in my case coding   and yours has different if statements.. but im also using a "midnight" theme  for the card... but for me it works as a toggle

```
  - entity: switch.b_building_lights
    name: Building Lights (LED)
    icon: hass:lightbulb
    secondary_info: last-updated
    card_mod: 
    style: |
            :host {
                {% if is_state(config.entity,'on') %}
                --card-mod-icon: mdi:shield-off-outline;
                --card-mod-icon-color: red;
                {% else %}
                --card-mod-icon: mdi:shield-remove-outline;
                --card-mod-icon-color: cyan;
                {% endif %}
            }
```

so it will go red and cyan  and change the icon  the bottom of my code is

```
title: Building
state_color: true
theme: midnight
show_header_toggle: false
```

now the coding that works for me in mine is
```    card_mod: null
    style: |
      :host {
      --card-mod-icon-color: 
      {% if states(config.entity) == 'on' %} 
        yellow;
      --card-mod-icon: mdi:car; 
      {% elif states(config.entity) == 'off' %}
        green;
      --card-mod-icon: mdi:star; 
      {% else %}
        blue;
      --card-mod-icon: mdi:car; 
      {% endif %}
      ;
      } 
```
 and for me this is how i started 

```
    card_mod: null
    style: |
      :host {
      --card-mod-icon-color: 
      {% if states(config.entity) == 'on' %} 
        yellow
      {% elif states(config.entity) == 'off' %}
        green
     {% else %}
        blue
      {% endif %}
      ;
      } 
```



see if that works and if i missed a step try what i did above

**Comment by comet424** [comment] 2022-06-02 17:12
and the way i have it  @ildar170975   is   yellow is on  green is off and blue means the device is offline

**Comment by comet424** [comment] 2022-06-02 17:20
@ildar170975 
also try using  
card_mod: null

i have found  if you have card_mod: 
it wont work  the null has to be there.. so give that a try too

**Comment by comet424** [comment] 2022-06-02 17:25
ok so i not that advanced with HA  and stuff

so i only know the  add on themes...

so youll have to step by step it better 

and do i add that to my switch

**Comment by ildar170975** [comment] 2022-06-02 17:28
OK, leave it.

**Comment by comet424** [comment] 2022-06-02 18:39
sorry couldnt help ya ):

**Comment by ildar170975** [comment] 2022-06-08 21:28
@thomasloven 
Please check this: https://github.com/thomasloven/lovelace-card-mod/issues/206#issuecomment-1150422022
There are some issues with `input_boolean`, `switch`, `sensor`, `device_tracker` & `zone`.

**Comment by ildar170975** [comment] 2022-06-13 14:47
> Can I help somehow, with examples, debugging?

Please create a small theme:
https://github.com/thomasloven/lovelace-card-mod/issues/187#issuecomment-1145112018

And add an Entities card with entities for DIFFERENT domains (sensor, input_number, ...).
For each row specify a style: https://github.com/thomasloven/lovelace-card-mod/issues/187#issuecomment-1145112018

Check the styles with a default theme and that custom theme..
