### ISSUE TITLE
—card-mod-icon no realtime update

### ISSUE THREAD

**Issue by Maddin1684** [thomasloven/lovelace-card-mod#335] opened 2023-12-30 16:10 UTC
My Home Assistant version: 2013.12.3

My lovelace configuration method (GUI or yaml): yaml

What I am doing: using —card-mod-icon to change icon with different states of entities

What I expected to happen: realtime update of the icon

What happened instead: icons doesn’t update in realtime. This works fine with the previous version of card_mod

**Minimal** steps to reproduce:

```
  - entity: binary_sensor.garagentur
     icon: mdi:garage-variant
    secondary_info: last-changed
    card_mod:
      style:
        hui-generic-entity-row:
          $: |
            .text-content:not(.info) {
               color:
                  {% if is_state(config.entity, 'off') %}
                   white
                   {% else %}
                   #ff4040
                 {% endif %}
                 ;
             }
            :host {
            {% if is_state(config.entity, 'off') %}
             --paper-item-icon-color: white;
             --card-mod-icon: mdi:garage-variant;
              {% else %}
             --paper-item-icon-color: #ff4040;
             --card-mod-icon: mdi:garage-open-variant;
                  {% endif %}
                  ;  
                  }
```

Error messages from the browser console:

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [x] Understand that this is achannel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by thomasloven** [comment] 2023-12-30 16:27
Still a duplicate of #333.

**Closed by thomasloven** 2023-12-30 16:27 UTC
