### ISSUE TITLE
2024.8: card_mod does not work for new mushroom-template-badge

### ISSUE THREAD

**Issue by felixmueller** [thomasloven/lovelace-card-mod#393] opened 2024-08-09 08:35 UTC
My Home Assistant version: 2024.8.0

My lovelace configuration method (GUI or yaml): GUI

What I am doing: trying to style new mushroom-template-badge

What I expected to happen: card_mod works

What happened instead: card_mod not supported

**Minimal** steps to reproduce:
Add mushroom-template-badge to badges area, try to add card_mod in code editor

```yaml
# The least amount of code possible to reproduce my error
type: custom:mushroom-template-badge
content: Hello
icon: mdi:mushroom
color: red
card_mod:
  style: |
    ha-card {
      margin: 10px;
    }
# End of code
```

Error messages from the browser console:
At path: card_mod -- Expected a value of type `never`, but received: `[object Object]`

<img width="823" alt="mushroom-template-badge-card_mod" src="https://github.com/user-attachments/assets/fb0c0fda-a5da-479e-aa45-4c31bcd16d1f">

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by ildar170975** [comment] 2024-08-09 12:54
This is not a bug of card-mod.
This is how Editor works.
If your style is applied - OK, you achieved the goal.

**Comment by felixmueller** [comment] 2024-08-09 16:27
Hi @ildar170975!
Not really - all other editors accept the fact that the card_mod element exists and show a little pencil icon in the editor button.
In this case, the card_mod element isn't accepted by the yaml editor - and the style seems not to be applied.

**Comment by ildar170975** [comment] 2024-08-09 16:38
@felixmueller 
Not that simple....
For some cards:
1. Card-mod code disappears after "type in card-mod code in editor - save the card - reopen card in editor":
```
type: tile
entity: sun.sun
card_mod:
  style: |
    ha-card {color: red}
```
2. Card-mod code simply disappears even before saving.

And these a "card-mod issues".

The issue you described is a tiny one & not directly related to card-mod.

Like this:
![image](https://github.com/user-attachments/assets/5d05fdd9-0bba-421c-a29d-e06e4c716870)

Or this w/o card-mod:
![image](https://github.com/user-attachments/assets/d662518a-3af4-422b-8786-7fc6b13004b5)

**Comment by lloydbayley** [comment] 2024-08-16 13:11
Agreed, it's not the same way as it was before but it is bound by the UI changes and so we can still use card-mod but we have to use things differently whilst remembering it's not the fault of card-mod.

I rearranged the badges that I needed to either animate or change background colours on etc into a separate Mushroom Chips card to handle them all.

For example, until I get around to piping it outside, when the dehumidifier tank in my library is full, the following code shows a flashing red badge on an otherwise (almost) invisible card. I say almost invisible because the card does take up a very small amount of space on the dashboard making it look like the card below is ever-so slightly lower. You can either put up with it like I do or move it to somewhere at the bottom of other cards so you don't see it.

```
type: custom:mushroom-chips-card
chips:
  - type: entity
    entity: binary_sensor.dehumidifier_tank
    name: Library Full
    content_info: name
    icon_color: red
    card_mod:
      style: |
        @keyframes blinker { 50% { opacity: 0; } }
        :host {
          --chip-background: red;
          --primary-text-color: white;
          --card-mod-icon-color: white;
          animation: blinker 1s linear infinite;
          {% if not is_state('binary_sensor.dehumidifier_tank', 'Full') %}
            display: none;
          {% else %}
            display: inline-block;
          {% endif %}
         color: white;
        }
```

Hopefully this will help some people 'roll their own' alternatives. It won't be for everyone but it might just help some people.

**Comment by 1iverea9er** [comment] 2024-08-20 08:40
I also failed to apply card-mod specifically to `custom:mushroom-template-badge`. I assume this is because in CSS it is no longer a `ha-card` as required for `card-mod`.

It seems `ha-card` is the key to the question of which elements to apply `card-mod` to at all. Does the author have any ideas on how to fix this?

**Comment by ildar170975** [comment] 2024-08-21 23:42
Seems that the initial question was [answered](https://github.com/thomasloven/lovelace-card-mod/issues/393#issuecomment-2277882653).
And other posts are about smth different.
Probably this is not a card-mod's issue/bug - this is a question to a particular custom card you are trying to style; these questions should be asked in Community first.
If you suspect that some custom card lost it's `ha-card` element - then it is better to ask in the card's Repo.
Suggest to close the issue.

**Comment by felixmueller** [comment] 2024-08-22 05:43
Unfortunately, my question has not been answered.
The main issue is that the editor does not accept the card_mod specification and throws a yellow error. This is not the case with all the other cards I style.
The next question is how the new HA badges can be styled at all. If I see this correctly, there is indeed a ha-card element.
It would be great if someone could work this out and report on their solution.
Many thanks

**Comment by ildar170975** [comment] 2024-08-22 10:17
> Unfortunately, my question has not been answered.
The main issue is that the editor does not accept the card_mod specification and throws a yellow error. This is not the case with all the other cards I style.

Yellow - is a warning, not an error.
If the card-mod code is applied in fact - do not bother about this warning (gosh, many users do not use UI editor at all since they have yaml-driven setups - and ofc they do not see these "errors" and live happily).
If the card-mod code is NOT applied -> then double check if the code IS SUPPOSED to be applied; sometimes a user tries to change a CSS property w/o "!important"; sometimes CSS properties should be changed for particular DOM elements, not to `ha-card`; sometimes a card does not have `ha-card` at all - and should be modded in another ways. Ask in Community for details since these issues COULD BE not "card-mod bugs".

> The next question is how the new HA badges can be styled at all

Due to this agreement:
![изображение](https://github.com/user-attachments/assets/1f17a856-b071-4346-9fbb-42642117159c)
all questions should be asked in Community.

**Comment by felixmueller** [comment] 2024-08-22 11:05
Alright. Will move further questions to community.

**Closed** 2024-08-22 11:05 UTC

**Comment by ildar170975** [comment] 2024-08-22 11:10
@felixmueller 
[Here is the main card-mod thread in Community.](https://community.home-assistant.io/t/card-mod-add-css-styles-to-any-lovelace-card/120744)
But mushrooms may probably have a separate thread, cannot give a link (not using mushrooms). Anyway, ask in that thread, people may give a hint.

**Comment by punisherdsm-tech** [comment] 2026-03-15 22:14
> Unfortunately, my question has not been answered. The main issue is that the editor does not accept the card_mod specification and throws a yellow error. This is not the case with all the other cards I style. The next question is how the new HA badges can be styled at all. If I see this correctly, there is indeed a ha-card element. It would be great if someone could work this out and report on their solution. Many thanks

Your just forget to install card-mod 4 aka lovelace. In hacs you must wrote: https://github.com/thomasloven/lovelace-card-mod#
