### ISSUE TITLE
I want to control the secondary-info with css, but I need help

### ISSUE THREAD

**Issue by thoath2** [thomasloven/lovelace-card-mod#418] opened 2024-12-20 19:29 UTC
Hello, 
i tried to use card-mod to control several thing, for example the color and the font-size of secondary-info.
This I tried:
<img width="768" alt="s10" src="https://github.com/user-attachments/assets/3bb6f44c-08a1-4695-8f84-85b9eb64fad2" />

I had success with controling of color of the secondary-info, but only with the parameter --secondary-text-color.
No success i have with the font-size of secondary-info. I would like to use the css-syntax. But I don't know how?
Can You show me a way, how i can configure it?
I would also like to control these 4 parameters for all entities on the card. This would also require me to set the font size and color for the value below.

**Comment by ildar170975** [comment] 2024-12-20 19:46
![image](https://github.com/user-attachments/assets/13a149f4-33f5-4238-b1e7-8cffb929c380)

Not a bug.
Suggest to close the issue & ask in Community.

**Comment by thoath2** [comment] 2024-12-20 20:06
Please tell me a place in Community, where i can ask my question?

**Comment by ildar170975** [comment] 2024-12-20 20:45
[This is the main card-mod thread.](https://community.home-assistant.io/t/card-mod-add-css-styles-to-any-lovelace-card/120744)
Suggest to check the 1st post -> link at the bottom titled "fantastic" -> multiple-entity-row, you will find there examples for this card (most probably including your case).

**Comment by thoath2** [comment] 2024-12-21 10:49
Oh thank You so much. I found a solution. And now i understand i more and more how card-mod works. In the screenshot i tried some Versions. 
<img width="777" alt="s13" src="https://github.com/user-attachments/assets/04bd3cfc-793d-475c-93fb-adde54c3ae44" />

**Closed** 2024-12-21 10:49 UTC

**Comment by thoath2** [comment] 2024-12-21 10:50
Now I close the issue. Thanks for ildar170975 for help.
